spring:
  profiles:
    active:
#      로컬에서 개발할 때 포트 설정
#      - dev
#      배포할 때 포트 설정
      - prod
# 나중에 실제로 배포할 때는 환경변수로 변경함

---
spring:
  config:
    activate:
      on-profile: dev
server:
  port: 8081

---
spring:
  config:
    activate:
      on-profile: prod
server:
  port: 5000